version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: smart_analyst_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: smart
      POSTGRES_DB: smart_analyst
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
